# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format
